export interface SeedOpportunity {
  id: string;
  title: string;
  organization: string;
  description: string;
  eligibility: string;
  deadline: string;
  country: string;
  category: string;
  applyLink: string;
  requiredDocuments: string[];
  field: string;
  degreeLevel?: string;
  applicationCount?: number;
  viewCount?: number;
}

export const seedOpportunities: SeedOpportunity[] = [
  // ── SCHOLARSHIP PLATFORMS ──────────────────────────────────────────────
  {
    id: "seed-nsp",
    title: "National Scholarship Portal (NSP)",
    organization: "Government of India",
    description: "Central hub for all Central & State Government scholarships in India. Single-window platform for application and disbursal.",
    eligibility: "Varies by scheme listed on NSP — check individual scheme criteria on the portal.",
    deadline: "Rolling — check official portal",
    country: "India",
    category: "Scholarships",
    applyLink: "https://scholarships.gov.in",
    requiredDocuments: ["As per selected scheme on NSP"],
    field: "All Fields",
  },
  {
    id: "seed-buddy4study",
    title: "Buddy4Study",
    organization: "Buddy4Study",
    description: "India's largest scholarship aggregator platform listing government and private scholarships across fields and education levels.",
    eligibility: "Varies by individual scholarship listed on the platform.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Scholarships",
    applyLink: "https://www.buddy4study.com",
    requiredDocuments: ["As per selected scholarship"],
    field: "All Fields",
  },
  {
    id: "seed-pragati",
    title: "AICTE PRAGATI Scholarship for Girl Students",
    organization: "AICTE (Govt of India)",
    description: "Scholarship for girl students pursuing engineering, diploma and technical education courses.",
    eligibility: "Female students enrolled in AICTE-approved technical/engineering institutions.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Scholarships",
    applyLink: "https://www.aicte-india.org/schemes/students-development-schemes",
    requiredDocuments: ["Admission proof", "Income certificate", "Category certificate (if applicable)"],
    field: "Engineering / Technical Education",
    degreeLevel: "Diploma/Bachelor",
  },
  {
    id: "seed-ugc",
    title: "UGC Scholarships & Fellowships",
    organization: "University Grants Commission",
    description: "Scholarships and fellowships for undergraduate, postgraduate and research students across India.",
    eligibility: "Varies by scheme — undergraduate, postgraduate or research scholars.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Fellowships",
    applyLink: "https://www.ugc.gov.in",
    requiredDocuments: ["As per selected scheme"],
    field: "All Fields",
  },
  {
    id: "seed-istem-women",
    title: "India Science & Technology — Women Scholarships",
    organization: "I-STEM / DST",
    description: "Curated STEM scholarships and fellowships specifically for women across research and academic stages.",
    eligibility: "Women students/researchers in STEM fields.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "STEM Programs",
    applyLink: "https://www.istem.gov.in",
    requiredDocuments: ["As per selected scheme"],
    field: "STEM",
  },
  {
    id: "seed-cbse-girl-child",
    title: "CBSE Single Girl Child Scholarship",
    organization: "CBSE",
    description: "Scholarship for meritorious single girl child students studying in CBSE-affiliated schools.",
    eligibility: "Single girl child, CBSE Class XII pass, admitted to Class XI.",
    deadline: "Rolling — check official portal",
    country: "India",
    category: "Scholarships",
    applyLink: "https://www.cbse.gov.in",
    requiredDocuments: ["Mark sheet", "Single girl child certificate"],
    field: "School Education",
    degreeLevel: "Class XI-XII",
  },
  {
    id: "seed-reliance-foundation",
    title: "Reliance Foundation Scholarships",
    organization: "Reliance Foundation",
    description: "Merit-based scholarships across disciplines with significant participation and outreach toward female students.",
    eligibility: "Merit-based; open to eligible undergraduate/postgraduate students.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Scholarships",
    applyLink: "https://www.reliancefoundation.org/scholarships",
    requiredDocuments: ["Academic records", "Income proof"],
    field: "All Fields",
  },
  {
    id: "seed-azim-premji",
    title: "Azim Premji Foundation Scholarships",
    organization: "Azim Premji Foundation",
    description: "Scholarships for girls from government schools across many Indian states.",
    eligibility: "Girl students studying in government schools in participating states.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Scholarships",
    applyLink: "https://azimpremjifoundation.org",
    requiredDocuments: ["School enrollment proof"],
    field: "School Education",
  },
  {
    id: "seed-vidya-lakshmi",
    title: "Vidya Lakshmi Portal",
    organization: "Government of India",
    description: "Single-window portal for students to access education loan and scholarship information from multiple banks/schemes.",
    eligibility: "Students seeking education loans or scholarship information.",
    deadline: "Rolling",
    country: "India",
    category: "Scholarships",
    applyLink: "https://www.vidyalakshmi.co.in",
    requiredDocuments: ["As per selected loan/scheme"],
    field: "All Fields",
  },
  {
    id: "seed-wemakescholars",
    title: "WeMakeScholars",
    organization: "WeMakeScholars",
    description: "Scholarship guidance and listings for Indian students studying in India and abroad.",
    eligibility: "Varies by listed scholarship.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Scholarships",
    applyLink: "https://www.wemakescholars.com",
    requiredDocuments: ["As per selected scholarship"],
    field: "All Fields",
  },

  // ── GOVERNMENT SCHEMES ──────────────────────────────────────────────────
  {
    id: "seed-bbbp",
    title: "Beti Bachao Beti Padhao (BBBP)",
    organization: "Government of India",
    description: "National scheme to promote education, safety, and empowerment of the girl child.",
    eligibility: "Girl children across India (scheme-level, not individual application).",
    deadline: "Ongoing scheme",
    country: "India",
    category: "STEM Programs",
    applyLink: "https://wcd.nic.in/bbbp-schemes",
    requiredDocuments: ["N/A — government scheme"],
    field: "Education & Welfare",
  },
  {
    id: "seed-ssy",
    title: "Sukanya Samriddhi Yojana (SSY)",
    organization: "Government of India",
    description: "Government savings scheme to fund a girl child's education and future needs.",
    eligibility: "Parents/guardians of a girl child under 10 years.",
    deadline: "Ongoing scheme",
    country: "India",
    category: "STEM Programs",
    applyLink: "https://www.india.gov.in/sukanya-samriddhi-yojana",
    requiredDocuments: ["Birth certificate", "Guardian ID proof"],
    field: "Savings / Education Fund",
  },
  {
    id: "seed-nsigse",
    title: "National Scheme of Incentive to Girls for Secondary Education (NSIGSE)",
    organization: "Ministry of Education, Govt of India",
    description: "Financial incentive scheme to encourage girls to continue secondary education.",
    eligibility: "Girls enrolled in secondary education under the scheme's criteria.",
    deadline: "Ongoing scheme",
    country: "India",
    category: "Scholarships",
    applyLink: "https://scholarships.gov.in",
    requiredDocuments: ["School enrollment proof"],
    field: "School Education",
  },
  {
    id: "seed-kgbv",
    title: "Kasturba Gandhi Balika Vidyalaya (KGBV)",
    organization: "Ministry of Education, Govt of India",
    description: "Residential schools for girls from disadvantaged communities to support secondary education.",
    eligibility: "Girls from disadvantaged communities eligible per scheme guidelines.",
    deadline: "Ongoing scheme",
    country: "India",
    category: "Scholarships",
    applyLink: "https://samagra.education.gov.in/kgbv.html",
    requiredDocuments: ["Community/category certificate"],
    field: "School Education",
  },

  // ── STEM / RESEARCH FELLOWSHIPS ─────────────────────────────────────────
  {
    id: "seed-vigyan-jyoti",
    title: "Vigyan Jyoti (DST)",
    organization: "Department of Science & Technology",
    description: "STEM camps, mentoring, and IIT visits for school girls in classes 9–12 to encourage STEM careers.",
    eligibility: "Girls in Classes 9–12 interested in STEM.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "STEM Programs",
    applyLink: "https://www.vigyanjyoti.dst.gov.in",
    requiredDocuments: ["School enrollment proof"],
    field: "STEM",
    degreeLevel: "Class 9-12",
  },
  {
    id: "seed-inspire-she",
    title: "INSPIRE-SHE Scholarship",
    organization: "Department of Science & Technology",
    description: "Scholarship for science students pursuing B.Sc. / Integrated M.Sc. programs.",
    eligibility: "Students pursuing B.Sc./Integrated M.Sc. in science subjects.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Scholarships",
    applyLink: "https://online-inspire.gov.in",
    requiredDocuments: ["Academic transcripts"],
    field: "Science",
    degreeLevel: "Bachelor",
  },
  {
    id: "seed-wise-kiran",
    title: "WISE-KIRAN (Women in Science & Engineering)",
    organization: "Department of Science & Technology",
    description: "Opportunities and support programs for women researchers and postgraduate students in science and engineering.",
    eligibility: "Women researchers and postgraduate students.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Fellowships",
    applyLink: "https://dst.gov.in/scientific-programmes/scientific-engineering-research/women-scientists-programs",
    requiredDocuments: ["Research proposal", "Academic CV"],
    field: "Science & Engineering",
    degreeLevel: "Postgraduate",
  },
  {
    id: "seed-wise-scope",
    title: "WISE-SCOPE Fellowship",
    organization: "Department of Science & Technology",
    description: "Fellowship supporting women returning to STEM careers after a break.",
    eligibility: "Women re-entering STEM careers after a career break.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Fellowships",
    applyLink: "https://dst.gov.in",
    requiredDocuments: ["Career break proof", "Research proposal"],
    field: "STEM",
  },
  {
    id: "seed-wos",
    title: "Women Scientist Scheme (WOS-A, WOS-B, WOS-C)",
    organization: "Department of Science & Technology",
    description: "Fellowships for women scientists and researchers across basic research (WOS-A), societal programs (WOS-B), and self-employment (WOS-C).",
    eligibility: "Women scientists/researchers meeting scheme-specific criteria.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Research Programs",
    applyLink: "https://dst.gov.in/scientific-programmes/scientific-engineering-research/women-scientists-programs",
    requiredDocuments: ["Research proposal", "Academic CV"],
    field: "Science & Research",
  },
  {
    id: "seed-serb-power",
    title: "SERB POWER Fellowship",
    organization: "Science & Engineering Research Board",
    description: "Fellowship promoting opportunities for women in research careers — for women faculty and researchers.",
    eligibility: "Women faculty and researchers in recognized institutions.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Fellowships",
    applyLink: "https://serb.gov.in/power",
    requiredDocuments: ["Research proposal", "Institutional affiliation proof"],
    field: "Research",
  },
  {
    id: "seed-bio-care",
    title: "Bio-CARe (DBT)",
    organization: "Department of Biotechnology",
    description: "Career advancement and re-entry program for women researchers in biotechnology.",
    eligibility: "Women researchers in biotechnology field.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Research Programs",
    applyLink: "https://dbtindia.gov.in",
    requiredDocuments: ["Research proposal"],
    field: "Biotechnology",
  },
  {
    id: "seed-ugc-pdf-women",
    title: "UGC Post-Doctoral Fellowship for Women",
    organization: "University Grants Commission",
    description: "Postdoctoral research fellowship exclusively for women scholars.",
    eligibility: "Women scholars pursuing postdoctoral research.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Fellowships",
    applyLink: "https://www.ugc.gov.in",
    requiredDocuments: ["PhD certificate", "Research proposal"],
    field: "All Fields",
    degreeLevel: "Postdoctoral",
  },

  // ── CONFERENCES ────────────────────────────────────────────────────────────
  {
    id: "seed-conf-vigyan-jyoti",
    title: "Vigyan Jyoti Program Events",
    organization: "Department of Science & Technology (DST)",
    description: "STEM camps, mentoring sessions, and IIT visits organized for school girls.",
    eligibility: "School girls in STEM-focused classes.",
    deadline: "Check official site for event dates",
    country: "India",
    category: "Conferences",
    applyLink: "https://vigyanjyoti.dst.gov.in",
    requiredDocuments: ["School enrollment proof"],
    field: "STEM",
  },
  {
    id: "seed-conf-west",
    title: "WEST (Women in Engineering, Science & Technology)",
    organization: "Office of the Principal Scientific Adviser & I-STEM",
    description: "Research networking events connecting women scientists across disciplines.",
    eligibility: "Women scientists and researchers.",
    deadline: "Check official site for event dates",
    country: "India",
    category: "Conferences",
    applyLink: "https://www.istem.gov.in/west",
    requiredDocuments: ["Registration via official site"],
    field: "Science & Technology",
  },
  {
    id: "seed-conf-ieee-wie",
    title: "IEEE Women in Engineering (WIE) India Events",
    organization: "IEEE India",
    description: "Events focused on engineering, AI, electronics, and computing for women in the field.",
    eligibility: "Open to engineers, students, and professionals.",
    deadline: "Check official site for event dates",
    country: "India",
    category: "Conferences",
    applyLink: "https://wie.ieee.org",
    requiredDocuments: ["Registration via official site"],
    field: "Engineering & Computing",
  },

  // ── INTERNSHIPS ──────────────────────────────────────────────────────────
  {
    id: "seed-aicte-internship-portal",
    title: "AICTE National Internship Portal",
    organization: "AICTE (Govt of India)",
    description: "Government-backed portal offering 1 lakh+ free and paid internships across government ministries, PSUs, and private companies (IBM, Cisco, Microsoft, ISRO, DRDO) for AICTE-approved students.",
    eligibility: "UG, PG, and Diploma students at AICTE-approved institutions across all streams.",
    deadline: "Rolling — registrations open throughout the year",
    country: "India",
    category: "Internships",
    applyLink: "https://internship.aicte-india.org",
    requiredDocuments: ["College ID / enrollment proof", "Resume"],
    field: "All Fields",
  },
  {
    id: "seed-aicte-women-in-tech-internship",
    title: "AICTE Women in Tech Internship Track",
    organization: "AICTE (Govt of India)",
    description: "A track within the AICTE National Internship Portal focused on women's participation in technology internships.",
    eligibility: "Female students enrolled at AICTE-approved technical institutions.",
    deadline: "Rolling — check official portal",
    country: "India",
    category: "Internships",
    applyLink: "https://internship.aicte-india.org",
    requiredDocuments: ["College ID / enrollment proof", "Resume"],
    field: "Technology",
  },

  // ── HACKATHONS ────────────────────────────────────────────────────────────
  {
    id: "seed-sih",
    title: "Smart India Hackathon (SIH)",
    organization: "Ministry of Education & AICTE",
    description: "India's largest nationwide hackathon where student teams solve real-world problem statements submitted by government departments, PSUs, and industry.",
    eligibility: "Students enrolled in Indian colleges/universities, team-based (typically 6 members), nominated via internal college hackathon.",
    deadline: "Rolling — annual cycle, problem statements released mid-year",
    country: "India",
    category: "Hackathons",
    applyLink: "https://sih.gov.in",
    requiredDocuments: ["College nomination via SPOC", "Team registration on SIH portal"],
    field: "Technology / Engineering / All Disciplines",
  },
  {
    id: "seed-sih-junior",
    title: "Smart India Hackathon Junior (SIH Junior)",
    organization: "Ministry of Education & AICTE",
    description: "A school-level version of Smart India Hackathon for students in Classes 6 to 12 to build innovative tech solutions (robotics, AI, apps, games).",
    eligibility: "Students in Classes 6–12, team-based participation.",
    deadline: "Rolling — check official site",
    country: "India",
    category: "Hackathons",
    applyLink: "https://sih.gov.in",
    requiredDocuments: ["School registration"],
    field: "STEM / Robotics / AI",
    degreeLevel: "Class 6-12",
  },
  {
    id: "seed-witchhunt",
    title: "WitchHunt — Women in Technology Challenge",
    organization: "HopeWorks Foundation",
    description: "A hackathon championing diversity in tech, focused on women building AI solutions across Education, Climate Action, Health, and Smart Cities tracks.",
    eligibility: "Open to women, including non-technical participants; teams self-formed.",
    deadline: "Rolling — check official site for current cycle dates",
    country: "India",
    category: "Hackathons",
    applyLink: "https://witchhunt.in",
    requiredDocuments: ["Team registration on official site"],
    field: "AI / Technology for Social Good",
  },

  // ── EXCHANGE PROGRAMS ─────────────────────────────────────────────────────
  {
    id: "seed-daad-wise",
    title: "DAAD WISE (Working Internships in Science and Engineering)",
    organization: "German Academic Exchange Service (DAAD)",
    description: "Fully funded 2-3 month research internship in Germany for Indian undergraduate students in Science, Engineering, and Mathematics.",
    eligibility: "Indian nationals enrolled at DAAD-partner institutions (IITs, NITs, IISERs, IIITs) in 5th/6th semester.",
    deadline: "Rolling — check official portal for next cohort",
    country: "Germany",
    category: "Exchange Programs",
    applyLink: "https://www.daaddelhi.org",
    requiredDocuments: ["Invitation letter from German supervisor", "Academic transcripts"],
    field: "Science, Engineering, Mathematics",
    degreeLevel: "Undergraduate",
  },
  {
    id: "seed-mitacs-globalink",
    title: "Mitacs Globalink Research Internship (AICTE-Mitacs, Canada)",
    organization: "Mitacs / AICTE",
    description: "Fully funded 12-week research internship at a Canadian university under faculty supervision, covering airfare, stipend, and insurance.",
    eligibility: "Undergraduate students at AICTE/UGC-approved Indian institutions.",
    deadline: "Rolling — check official portal for current cycle",
    country: "Canada",
    category: "Exchange Programs",
    applyLink: "https://www.mitacs.ca/en/programs/globalink/globalink-research-internship",
    requiredDocuments: ["Academic transcripts", "CV", "Reference letter"],
    field: "Science, Engineering, Mathematics",
    degreeLevel: "Undergraduate",
  },
];
